name: 'Downlaod coverage from GCS and compare'
description: 'Compare code coverage between base and head branches using coverage reports from Google Cloud Storage'
author: 'baobab soluciones'

inputs:
  gcp_credentials:
    description: 'Google Cloud Service Account credentials JSON'
    required: true
  min_coverage:
    description: 'Minimum required coverage percentage'
    required: false
    default: '00'
  github_token:
    description: 'GitHub token for PR comments'
    required: true
    default: 'fake_token'
  gcp_bucket:
    description: 'GCP bucket name where coverage reports are stored'
    required: true
  show_missing_lines:
    description: 'Show missing lines in coverage report'
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'check-square'
  color: 'orange'
