name: 'Coverage Comparison Action'
description: 'Compare code coverage between base and head branches using coverage reports from Google Cloud Storage'
author: 'baobab soluciones'

inputs:
  gcp_credentials:
    description: 'Google Cloud Service Account credentials JSON'
    required: true
  min_coverage:
    description: 'Minimum required coverage percentage'
    required: false
    default: '80'
  github_token:
    description: 'GitHub token for PR comments'
    required: true
    default: 'fake_token'
  gcp_bucket:
    description: 'GCP bucket name where coverage reports are stored'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'percent'
  color: 'green'
