name: Release

on:
  push:
    tags:
      - 'build*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create release tag
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Add built files
          git add dist/
          git commit -m "Build for ${{ github.ref_name }}"
          git push origin HEAD:master

          # Create clean version tag (remove 'build' prefix)
          VERSION_TAG="${{ github.ref_name }}"
          CLEAN_TAG="${VERSION_TAG/build/v}"

          git tag -a "$CLEAN_TAG" -m "Release $CLEAN_TAG"
          git push origin "$CLEAN_TAG"
