name: Test Coverage Action

on:
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Coverage Comparison
        uses: ./ # Uses an action in the root directory
        with:
          gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
          base_coverage_path: 'coverage/main/coverage.xml'
          head_coverage_path: 'coverage/pr/coverage.xml'
          min_coverage: '80'
