name: Unit Tests

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm test -- --coverage --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_DIR: coverage
          JEST_JUNIT_OUTPUT_NAME: coverage.xml
          JEST_JUNIT_CLASSNAME: '{filepath}'
          JEST_JUNIT_TITLE: '{title}'

      - name: Upload coverage report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: coverage/lcov-report/
          retention-days: 7

      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-xml
          path: coverage/coverage.xml
          retention-days: 7

      - name: Check coverage thresholds
        run: |
          COVERAGE=$(node -p "require('./coverage/coverage-summary.json').total.lines.pct")
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Coverage ($COVERAGE%) is below the required threshold (70%)"
            exit 1
          fi
