name: Unit Tests

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm test -- --coverage --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_DIR: coverage
          JEST_JUNIT_OUTPUT_NAME: junit.xml
          JEST_JUNIT_CLASSNAME: '{filepath}'
          JEST_JUNIT_TITLE: '{title}'
          JEST_JUNIT_INCLUDE_CONSOLE_OUTPUT: true

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage/clover.xml
            coverage/cobertura-coverage.xml
            coverage/junit.xml
            coverage/lcov.info
            coverage/coverage-summary.json
          retention-days: 7

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: coverage/lcov-report/
          retention-days: 7

      - name: Check coverage thresholds
        run: |
          COVERAGE=$(node -p "require('./coverage/coverage-summary.json').total.lines.pct")
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Coverage ($COVERAGE%) is below the required threshold (70%)"
            exit 1
          fi

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Get repository name
        id: repo-name
        run: echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

      - name: Upload to GCE bucket - authenticate
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload to GCE bucket - upload coverage reports
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'coverage/cobertura-coverage.xml'
          destination: '${{ secrets.GCP_COVERAGE_BUCKET }}/${{ steps.repo-name.outputs.repo_name }}/${{ github.ref_name }}/${{ steps.timestamp.outputs.timestamp }}'
