name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - master
      - develop

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: |
          npm test -- --coverage
          mv coverage/cobertura-coverage.xml coverage/coverage.xml

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/coverage.xml
          retention-days: 7

      - name: Check coverage thresholds
        run: |
          COVERAGE=$(node -p "const xml = require('fs').readFileSync('coverage/coverage.xml', 'utf8'); const match = xml.match(/line-rate=\"([0-9.]+)\"/); (parseFloat(match[1]) * 100).toFixed(2);")
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Coverage ($COVERAGE%) is below the required threshold (70%)"
            exit 1
          fi

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Get repository name
        id: repo-name
        run: echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

      - name: Get branch name
        id: branch-name
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Upload to GCE bucket - authenticate
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload to GCE bucket - upload coverage reports
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'coverage/coverage.xml'
          destination: '${{ secrets.GCP_COVERAGE_BUCKET }}/${{ steps.repo-name.outputs.repo_name }}/${{ steps.branch-name.outputs.branch }}/${{ steps.timestamp.outputs.timestamp }}'

  compare-coverage:
    runs-on: ubuntu-latest
    needs: [unit-test]
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build action
        run: npm run build

      - name: Compare coverage
        uses: ./
        with:
          gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
          gcp_bucket: ${{ secrets.GCP_COVERAGE_BUCKET }}
